export { default as LandingPage } from './LandingPage';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as ForgotPassword } from './ForgotPassword';
export { default as ResetPassword } from './ResetPassword';
export { default as Dashboard } from './Dashboard';
export { default as MyProfile } from './MyProfile';
export { default as CreateUser } from './CreateUser';
export { default as ManageUsers } from './ManageUsers';
export { default as EditUser } from './EditUser';
export { default as CreateProperty } from './CreateProperty';
export { default as ManageProperties } from './ManageProperties';
export { default as EditProperty } from './EditProperty';
export { default as AssociateProperties } from './AssociateProperties';
export { default as MyProperties } from './MyProperties';
export { default as Error404 } from './Error404'
