import createNumberMask from 'text-mask-addons/dist/createNumberMask';

const CodMask = createNumberMask({
    prefix: 'PD-',
    includeThousandsSeparator: false,
    integerLimit: 9,
    allowLeadingZeroes: true
})

const AreaMask = createNumberMask({
    prefix: '',
    allowDecimal: true,
    requireDecimal: true
})

const CurrencyMask = createNumberMask({
    prefix: '',
    thousandsSeparatorSymbol: '.'
})

export const inputUsersProps = [
    {
        id: "IdName",
        name: "name",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-user",
        errorMessage: "Por favor, ingrese un nombre válido!!! (Letras y espacios en blanco)",
        label: "Nombres",
        pattern: "^[A-Za-zÑñÁáÉéÍíÓóÚúÜü\\s]+$",
        required: true,
    },
    {
        id: "IdSurname",
        name: "surname",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-user",
        errorMessage: "Por favor, ingrese un apellido válido!!! (Letras y espacios en blanco)",
        label: "Apellidos",
        pattern: "^[A-Za-zÑñÁáÉéÍíÓóÚúÜü\\s]+$",
        required: true,
    },
    {
        id: "IdId_type",
        name: "id_type",
        type: "select",
        className: "col-10 col-sm-5 m-auto my-2",
        label: "Tipo de Documento",
        required: true,
    },
    {
        id: "IdId_number",
        name: "id_number",
        type: "number",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-fingerprint",
        errorMessage: "Por favor, ingrese un número de documento válido!!! (Números enteros sin comas ni puntos - Ej: 1145102365)",
        label: "Nro. de Documento",
        pattern: "^[0-9]+$",
        required: true,
    },
    {
        id: "IdEmail",
        name: "email",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-at",
        errorMessage: "Por favor, ingrese un correo electrónico válido!!! (Ej: ejemplo@mail.com)",
        label: "Correo Electrónico",
        pattern: "^(\\w+[/./-]?){1,}@[a-z]+[/.]\\w{2,}$",
        required: true,
    },
    {
        id: "IdPhone",
        name: "phone",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-phone",
        errorMessage: "Por favor, ingrese un número de teléfono válido!!! (Ej: (310) 654-3210 - Entre paréntesis indicativo fijo o celular)",
        label: "Teléfono",
        pattern: "^[(][1-9][0-9]{2}[)]\\s[1-9][0-9]{2}[-][0-9]{4}$",
        mask: ['(', /[1-9]/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/],
        required: true,
    },
    {
        id: "IdAddress",
        name: "address",
        type: "text",
        className: "col-10 col-sm-11 m-auto my-2",
        icon: "fa-solid fa-location-dot",
        errorMessage: "Por favor, ingrese una dirección válida!!! (Ejs: Calle 12 # 34 - 56, Carrera 123a # 45b - 67)",
        label: "Dirección",
        pattern: "^(([C][a][l][l][e]\\s)|([C][a][r][r][e][r][a]\\s))[1-9]([0-9]+)?([a-z])?\\s[#]\\s[1-9]([0-9]+)?([a-z])?\\s[-]\\s[1-9]([0-9]+)?$",
        required: true,
    },
];

export const inputUsersRegisterProps = [
    {
        id: "IdName",
        name: "name",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-user",
        errorMessage: "Por favor, ingrese un nombre válido!!! (Letras y espacios en blanco)",
        label: "Nombres",
        pattern: "^[A-Za-zÑñÁáÉéÍíÓóÚúÜü\\s]+$",
        required: true,
    },
    {
        id: "IdSurname",
        name: "surname",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-user",
        errorMessage: "Por favor, ingrese un apellido válido!!! (Letras y espacios en blanco)",
        label: "Apellidos",
        pattern: "^[A-Za-zÑñÁáÉéÍíÓóÚúÜü\\s]+$",
        required: true,
    },
    {
        id: "IdId_type",
        name: "id_type",
        type: "select",
        className: "col-10 col-sm-5 m-auto my-2",
        label: "Tipo de Documento",
        required: true,
    },
    {
        id: "IdId_number",
        name: "id_number",
        type: "number",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-fingerprint",
        errorMessage: "Por favor, ingrese un número de documento válido!!! (Números enteros 0-9)",
        label: "Nro. de Documento",
        pattern: "^[0-9]+$",
        required: true,
    },
    {
        id: "IdEmail",
        name: "email",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-at",
        errorMessage: "Por favor, ingrese un correo electrónico válido!!! (ejemplo@mail.com)",
        label: "Correo Electrónico",
        pattern: "^(\\w+[/./-]?){1,}@[a-z]+[/.]\\w{2,}$",
        required: true,
    },
    {
        id: "IdPassword",
        name: "password",
        type: "password",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-key",
        errorMessage: "La contraseña debe tener una longitud mínima de 8; contener al menos 1 mayuscula, 1 minuscula, 1 número y un caracter especial!!!",
        label: "Contraseña",
        pattern: "^(?=.{8,}$)(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])((?=.*\\W)|(?=.*_)).*$",
        required: true,
    },
    {
        id: "IdPhone",
        name: "phone",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-phone",
        errorMessage: "Por favor, ingrese un tipo de documento válido!!! (Números enteros 0-9)",
        label: "Teléfono",
        pattern: "^[(][1-9][0-9]{2}[)]\\s[1-9][0-9]{2}[-][0-9]{4}$",
        mask: ['(', /[1-9]/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/],
        required: true,
    },
    {
        id: "IdAddress",
        name: "address",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "bi bi-geo-alt-fill",
        errorMessage: "Por favor, ingrese una dirección válida!!! (Ejs: Calle 12 # 34 - 56, Carrera 123a # 45b - 67)",
        label: "Dirección",
        pattern: "^(([C][a][l][l][e]\\s)|([C][a][r][r][e][r][a]\\s))[1-9]([0-9]+)?([a-z])?\\s[#]\\s[1-9]([0-9]+)?([a-z])?\\s[-]\\s[1-9]([0-9]+)?$",
        required: true,
    },
];

export const inputPrediosProps = [
    {
        id: "IdCode",
        name: "code",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-barcode",
        errorMessage: "Por favor, ingrese un código válido!!! (Ej: PD-123456789)",
        label: "Código",
        pattern: "^[P][D][-][0-9]{9}$",
        mask: CodMask,
        required: true,
    },
    {
        id: "IdOwner_name",
        name: "owner_name",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-user",
        errorMessage: "Por favor, ingrese un nombre válido!!! (Letras y espacios en blanco)",
        label: "Nombre del Propietario",
        pattern: "^[A-Za-zÑñÁáÉéÍíÓóÚúÜü\\s]+$",
        required: true,
    },
    {
        id: "IdOwner_id_number",
        name: "owner_id_number",
        type: "number",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-fingerprint",
        errorMessage: "Por favor, ingrese un número de documento válido!!! (Números enteros 0-9)",
        label: "Nro. Documento del Propietario",
        pattern: "^[0-9]+$",
        required: true,
    },
    {
        id: "IdOwner_email",
        name: "owner_email",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-at",
        errorMessage: "Por favor, ingrese un correo electrónico válido!!! (Ej: ejemplo@mail.com)",
        label: "Correo Electrónico",
        pattern: "^(\\w+[/./-]?){1,}@[a-z]+[/.]\\w{2,}$",
        required: true,
    },
    {
        id: "IdBuilt_area",
        name: "built_area",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-building",
        errorMessage: "Por favor, ingrese un dato válido!!! (2 cifras decimales. Ejs: 10.00, 10.50)",
        label: "Área Construida (M²)",
        pattern: "^[1-9]([0-9]{1,2})?(([,][0-9]{3})+)?[.][0-9]{2}$",
        mask: AreaMask,
        required: true,
    },
    {
        id: "IdTotal_area",
        name: "total_area",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-building",
        errorMessage: "Por favor, ingrese un dato válido!!! (2 cifras decimales. Ejs: 10.00, 10.50)",
        label: "Área Total (M²)",
        pattern: "^[1-9]([0-9]{1,2})?(([,][0-9]{3})+)?[.][0-9]{2}$",
        mask: AreaMask,
        required: true,
    },
    {
        id: "IdProperty_value",
        name: "property_value",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-dollar-sign",
        errorMessage: "Por favor, ingrese un valor!!!",
        label: "Valor del Predio",
        pattern: "^[1-9][0-9.]*$",
        mask: CurrencyMask,
        required: true,
    },
    {
        id: "IdTax_value",
        name: "tax_value",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-dollar-sign",
        errorMessage: "Por favor, ingrese un valor!!!",
        label: "Valor del Impuesto Predial",
        pattern: "^[1-9][0-9.]*$",
        mask: CurrencyMask,
        required: true,
    },
    {
        id: "IdProperty_address",
        name: "property_address",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-location-dot",
        errorMessage: "Por favor, ingrese una dirección válida!!! (Ejs: Calle 12 # 34 - 56, Carrera 123a # 45b - 67)",
        label: "Dirección",
        pattern: "^(([C][a][l][l][e]\\s)|([C][a][r][r][e][r][a]\\s))[1-9]([0-9]+)?([a-z])?\\s[#]\\s[1-9]([0-9]+)?([a-z])?\\s[-]\\s[1-9]([0-9]+)?$",
        required: true,
    },
    {
        id: "IdNeighborhood",
        name: "neighborhood",
        type: "text",
        className: "col-10 col-sm-5 m-auto my-2",
        icon: "fa-solid fa-location-dot",
        errorMessage: "Por favor, ingrese un barrio válido!!!",
        label: "Barrio",
        pattern: "^[A-Za-z0-9ÑñÁáÉéÍíÓóÚúÜü\\s]+$",
        required: true,
    },
];

export const inputDateProps = [
    {
        id: "IdPayment_date_1",
        name: "payment_date_1",
        type: "date",
        className: "col-10 col-sm-5",
        errorMessage: "Por favor, ingrese una fecha válida!!!",
        label: "Fecha de Pago Máxima:",
        required: true,
    },
    {
        id: "IdPayment_date_2",
        name: "payment_date_2",
        type: "date",
        className: "col-10 col-sm-5",
        errorMessage: "Por favor, ingrese una fecha válida!!!",
        label: "Fecha de Pago para descuento del 40%:",
        required: true,
    },
    {
        id: "IdPayment_date_3",
        name: "payment_date_3",
        type: "date",
        className: "mb-3 col-10 col-sm-5",
        errorMessage: "Por favor, ingrese una fecha válida!!!",
        label: "Fecha de pago para descuento del 20%:",
        required: true,
    },
]

export const inputConvenioProps = [
    {
        id: "IdDown_payment",
        name: "down_payment",
        type: "select",
        inputClass: "col-10 col-sm-5 m-auto my-3",
        labelClass: " text-center col-10 col-sm-5 m-auto",
        label: "Cuota Inicial:",
        required: true,
    },
    {
        id: "IdDown_payment_value",
        name: "down_payment_value",
        type: "text",
        inputClass: "col-10 col-sm-5 m-auto my-3",
        labelClass: " text-center col-10 col-sm-5 m-auto",
        icon: "fa-solid fa-dollar-sign",
        errorMessage: "Por favor, ingrese un valor!!!",
        label: "Valor Cuota Inicial:",
        mask: CurrencyMask,
        required: true,
    },
    {
        id: "IdNumber_of_payments",
        name: "number_of_payments",
        type: "select",
        inputClass: "col-10 col-sm-5 m-auto my-3",
        labelClass: " text-center col-10 col-sm-5 m-auto",
        label: "Número de cuotas:",
        required: true,
    },
    {
        id: "IdPayments_value",
        name: "payments_value",
        type: "text",
        inputClass: "col-10 col-sm-5 m-auto my-3",       
        labelClass: " text-center col-10 col-sm-5 m-auto",
        icon: "fa-solid fa-dollar-sign",
        errorMessage: "Por favor, ingrese un valor!!!",
        label: "Valor de cuota:",
        mask: CurrencyMask,
        required: true,
    }
]
